version: "3"

services:
  redis_1:
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    restart: always
    environment:
      - REDIS_PORT=8001
    ports:
      - '8001:8001'       #服务端口
      - '18001:18001'   #集群端口

  redis_2:
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    restart: always
    environment:
      - REDIS_PORT=8002
    ports:
      - '8002:8002'       #服务端口
      - '18002:18002'   #集群端口


  redis_3:
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    restart: always
    environment:
      - REDIS_PORT=8003
    ports:
      - '8003:8003'       #服务端口
      - '18003:18003'   #集群端口

  redis_4:
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    restart: always
    environment:
      - REDIS_PORT=8004
    ports:
      - '8004:8004'       #服务端口
      - '18004:18004'   #集群端口

# 集群配置方法
# docker run --rm -it inem0o/redis-trib create --replicas 1 172.19.165.222:8001 172.19.165.222:8002 172.19.165.222:8003 172.19.165.222:8004

