version: "2"
services:
  master:
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    container_name: redis-cluster_master
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
  slave_1:
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    container_name: redis-cluster_slave_1
    command: redis-server /etc/redis/redis.conf --slaveof redis-master 6379
    links:
      - master:redis-master
    ports:
      - "6380:6379"
  slave_2:
    build:
      context: ./
      dockerfile: redis/Dockerfile
    container_name: redis-cluster_slave_2
    command: redis-server /etc/redis/redis.conf --slaveof redis-master 6379
    links:
      - master:redis-master
    ports:
      - "6381:6379"
  sentinel_1:
    build:
      context: ./
      dockerfile: redis-sentinel/Dockerfile
    container_name: redis-cluster_sentinel_1
    command: redis-sentinel /etc/redis/sentinel.conf
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave_1
      - slave_2
    ports:
      - "6390:6379"
      - "26390:26379"
  sentinel_2:
    build:
      context: ./
      dockerfile: redis-sentinel/Dockerfile
    container_name: redis-cluster_sentinel_2
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave_1
      - slave_2
    ports:
      - "6391:6379"
      - "26391:26379"
  sentinel_3:
    build:
      context: ./
      dockerfile: redis-sentinel/Dockerfile
    container_name: redis-cluster_sentinel_3
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave_1
      - slave_2
    ports:
      - "6392:6379"
      - "26392:26379"